server:
  port: 8080

spring:
  application:
    name: mini-banking-app
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driverClassName: org.h2.Driver
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
#    defer-datasource-initialization: true
#  flyway:
#    enabled: true
#    locations: classpath:db/migration
#    baseline-on-migrate: true

jwt:
  secret: PN7g9X$K2mF#qL8zR4vJ@bH3wY6tA5cE
  expiration: 86400000

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
